spring:
  datasource:
    # Sử dụng biến môi trường để bảo mật thông tin (Render/Railway sẽ tự điền nếu bạn cấu hình)
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.rgilyeocaabbppzoqzln}
    password: ${SPRING_DATASOURCE_PASSWORD:Okitasouji5}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Thêm cấu hình này để tránh lỗi khi dùng Pooler của Supabase
        temp:
          use_jdbc_metadata_defaults: false

server:
  # CỰC KỲ QUAN TRỌNG: Render/Railway cấp port ngẫu nhiên, không phải luôn là 8080
  port: ${PORT:8080}
